[package]
name = "tonic_prometheus_layer"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.11.0"
tower = "0.4.13"
log = "0.4.21"
pin-project = "1.1.5"
once_cell = "1.19.0"
prometheus = "0.13.4"
thiserror = "1.0.61"